### ISSUE TITLE
安卓example跑不起来

### ISSUE THREAD

**Issue by Crazz-Joe** [FlutterAds/flutter_gromore_ads#11]
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (4 weeks ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

D/PluginDelegate(21360): MethodChannel onMethodCall method:initAd arguments:{appId=5216573, config=android_config_5216573.json}
W/System.err(21360): java.io.FileNotFoundException: android_config_5216573.json
W/System.err(21360): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(21360): 	at android.content.res.AssetManager.open(AssetManager.java:904)
W/System.err(21360): 	at android.content.res.AssetManager.open(AssetManager.java:881)
W/System.err(21360): 	at com.zero.flutter_gromore_ads.utils.FileUtils.getJson(FileUtils.java:23)
W/System.err(21360): 	at com.zero.flutter_gromore_ads.PluginDelegate.initAd(PluginDelegate.java:178)
W/System.err(21360): 	at com.zero.flutter_gromore_ads.PluginDelegate.onMethodCall(PluginDelegate.java:85)
W/System.err(21360): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(21360): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(21360): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(21360): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(21360): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(21360): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(21360): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(21360): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(21360): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
W/System.err(21360): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21360): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)

还有一些其他错误  大佬麻烦看下

**Comment by Crazz-Joe** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libtobEmbedEncryptForM.so" not found
E/TeaLog  (13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/TeaLog  (13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/TeaLog  (13973): 	at java.lang.System.loadLibrary(System.java:1661)
E/TeaLog  (13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.<clinit>(Unknown Source:2)
E/TeaLog  (13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.a(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.a.n(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.q.h(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.a(Unknown Source:2)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.b(Unknown Source:18)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.a(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_int108.d$b.run(Unknown Source:7)
E/TeaLog  (13973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)

**Comment by Crazz-Joe** [comment]
U SHALL NOT PASS!
E/TeaLog  (13973): java.lang.UnsatisfiedLinkError: dlopen failed: library "libtobEmbedEncryptForM.so" not found
E/TeaLog  (13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/TeaLog  (13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/TeaLog  (13973): 	at java.lang.System.loadLibrary(System.java:1661)
E/TeaLog  (13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.<clinit>(Unknown Source:2)
E/TeaLog  (13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.a(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.a.n(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.q.h(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.a(Unknown Source:2)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.b(Unknown Source:18)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_try19.s.a(Unknown Source:0)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_int108.d$b.run(Unknown Source:7)
E/TeaLog  (13973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/TeaLog  (13973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/TeaLog  (13973): 	at java.lang.Thread.run(Thread.java:1012)
20
E/TeaLog  (13973): ********** --==-- 注意：GroMore so库【tobEmbedEncryptForM】未打进apk中，请检查打包环节 --==-- **********

**Comment by Crazz-Joe** [comment]
No implementation found for byte[] com.bytedance.mapplog.util.TTEncryptUtils.ttEncrypt(byte[], int) (tried Java_com_bytedance_mapplog_util_TTEncryptUtils_ttEncrypt and Java_com_bytedance_mapplog_util_TTEncryptUtils_ttEncrypt___3BI)
W/System.err(13973): java.lang.UnsatisfiedLinkError: No implementation found for byte[] com.bytedance.mapplog.util.TTEncryptUtils.ttEncrypt(byte[], int) (tried Java_com_bytedance_mapplog_util_TTEncryptUtils_ttEncrypt and Java_com_bytedance_mapplog_util_TTEncryptUtils_ttEncrypt___3BI)
W/System.err(13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.ttEncrypt(Native Method)
W/System.err(13973): 	at com.bytedance.mapplog.util.TTEncryptUtils.a(Unknown Source:0)
W/System.err(13973): 	at bykvm_19do.bykvm_19do.bykvm_new1.bykvm_19do.bykvm_byte12b.b.a(Unknown Source:60)
W/System.err(13973): 	at bykvm_19do.bykvm_19do.bykvm_new1.bykvm_19do.bykvm_byte12b.b.a(Unknown Source:26)
W/System.err(13973): 	at bykvm_19do.bykvm_19do.bykvm_new1.bykvm_19do.bykvm_new1.d.b(Unknown Source:101)
W/System.err(13973): 	at bykvm_19do.bykvm_19do.bykvm_new1.bykvm_19do.bykvm_new1.d.a(Unknown Source:5)
W/System.err(13973): 	at bykvm_19do.bykvm_19do.bykvm_new1.bykvm_19do.bykvm_byte12b.d.run(Unknown Source:13)
W/System.err(13973): 	at android.os.Handler.handleCallback(Handler.java:942)
W/System.err(13973): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(13973): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(13973): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(13973): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Crazz-Joe** [comment]
U SHALL NOT PASS!
E/TeaLog  (13973): java.lang.SecurityException: getDeviceId: The uid 10159 does not meet the requirements to access device identifiers.
E/TeaLog  (13973): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
E/TeaLog  (13973): 	at android.os.Parcel.createException(Parcel.java:2995)
E/TeaLog  (13973): 	at android.os.Parcel.readException(Parcel.java:2978)
E/TeaLog  (13973): 	at android.os.Parcel.readException(Parcel.java:2920)
E/TeaLog  (13973): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceIdWithFeature(ITelephony.java:10713)
E/TeaLog  (13973): 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:2061)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.i0.a(Unknown Source:10)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.r.a(Unknown Source:53)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.k2.e(Unknown Source:287)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.v1.handleMessage(Unknown Source:182)
E/TeaLog  (13973): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/TeaLog  (13973): 	at android.os.Looper.loopOnce(Looper.java:201)
E/TeaLog  (13973): 	at android.os.Looper.loop(Looper.java:288)
E/TeaLog  (13973): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Crazz-Joe** [comment]
PluginDefaultAdManager(13973): Not ready, no manager
E/TeaLog  (13973): U SHALL NOT PASS!
E/TeaLog  (13973): java.lang.NullPointerException: Attempt to get length of null array
E/TeaLog  (13973): 	at android.util.Base64.encode(Base64.java:496)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.s.a(Unknown Source:98)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.s.a(Unknown Source:23)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.z1.d(Unknown Source:73)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.t1.h(Unknown Source:44)
E/TeaLog  (13973): 	at bykvm_19do.bykvm_19do.bykvm_19do.v1.handleMessage(Unknown Source:151)
E/TeaLog  (13973): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/TeaLog  (13973): 	at android.os.Looper.loopOnce(Looper.java:201)
E/TeaLog  (13973): 	at android.os.Looper.loop(Looper.java:288)
E/TeaLog  (13973): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/TeaLog  (13973): r worked:false 10000
I/TeaLog  (13973): c worked:false 180000
I/TeaLog  (13973): p worked:false 60000
V/Zeus/init(13973): PluginManager parsePluginsJson

**Comment by Crazz-Joe** [comment]
FATAL EXCEPTION: gm_t_executor: # 3
E/AndroidRuntime(13973): Process: com.example.polystar, PID: 13973
E/AndroidRuntime(13973): java.lang.UnsatisfiedLinkError: dlopen failed: library "libnotpluginpro.so" not found
E/AndroidRuntime(13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(13973): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(13973): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(13973): 	at com.bytedance.notpluginpro.tmapcloaknotplugin.<clinit>(Unknown Source:23)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.b.b(Unknown Source:7)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.b.<init>(Unknown Source:24)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.b.c(Unknown Source:34)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.c.a(Unknown Source:8)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.c.a(Unknown Source:0)
E/AndroidRuntime(13973): 	at bykvm_19do.bykvm_19do.bykvm_if122.bykvm_19do.bykvm_long108.c$d.run(Unknown Source:90)
E/AndroidRuntime(13973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(13973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(13973): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by Crazz-Joe** [comment]
c worked:false 60000
W/System.err(13973): java.lang.RuntimeException: Please init Zeus first!
W/System.err(13973): 	at com.bytedance.pangle.Zeus.getPlugin(Unknown Source:217)
W/System.err(13973): 	at com.bytedance.pangle.g$1.a(Unknown Source:1083)
W/System.err(13973): 	at com.bytedance.pangle.b.b.a(Unknown Source:62)
W/System.err(13973): 	at com.bytedance.pangle.plugin.b.a(Unknown Source:300)
W/System.err(13973): 	at com.bytedance.pangle.plugin.b.a(Unknown Source:1163)
W/System.err(13973): 	at com.bytedance.pangle.plugin.Plugin.install(Unknown Source:591)
W/System.err(13973): 	at com.bytedance.pangle.plugin.a.a(Unknown Source:48)
W/System.err(13973): 	at com.bytedance.pangle.plugin.a.run(Unknown Source:28)
W/System.err(13973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err(13973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err(13973): 	at java.lang.Thread.run(Thread.java:1012)
W/Zeus/install(13973): PluginInstaller com.byted.pangle install failed.
W/Zeus/install(13973): com.bytedance.pangle.plugin.b$a: 安装包签名校验失败[1]
W/Zeus/install(13973): 	at com.bytedance.pangle.plugin.b.a(Unknown Source:1165)
W/Zeus/install(13973): 	at com.bytedance.pangle.plugin.Plugin.install(Unknown Source:591)
W/Zeus/install(13973): 	at com.bytedance.pangle.plugin.a.a(Unknown Source:48)
W/Zeus/install(13973): 	at com.bytedance.pangle.plugin.a.run(Unknown Source:28)
W/Zeus/install(13973): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/Zeus/install(13973): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/Zeus/install(13973): 	at java.lang.Thread.run(Thread.java:1012)
W/Zeus/install(13973): Caused by: java.lang.RuntimeException: 安装包签名校验失败[1]
W/Zeus/install(13973): 	at com.bytedance.pangle.plugin.b.a(Unknown Source:1160)
W/Zeus/install(13973): 	... 6 more

**Comment by Crazz-Joe** [comment]
问了原生开发安卓的朋友，经过排查是自己的问题。因为是intel的mac 所以模拟器是x86的。因为穿山甲的sdk里的so库不支持x86的，所以打包不进去apk。换成真机debug或者换成m1的mac就好了

**Comment by BytesZero** [comment]
嗯嗯，好的
