### ISSUE TITLE
升级到2.0.0之后，Gromore的开屏广告一直返回【广告位ID不合法】

### ISSUE THREAD

**Issue by KuangGang** [FlutterAds/flutter_gromore_ads#12]
之前的版本同样的代码是没问题的。但是接入完成2.0.0会报这个错误。
```
-[FGMSplashPage splashAdLoadFail:error:]-error:Error Domain=BUSplashAdDomain Code=1 "data analysis error" UserInfo={internal_reason={
    desc = "\U5e7f\U544a\U4f4dID\U4e0d\U5408\U6cd5";
    reason = 0;
    "request_id" = "E1E79DCD-23B0-4121-B4A3-A8EECB942550";
    "status_code" = 40006;
}, origin_error_code=10002000, extra_reason=广告位ID不合法, NSLocalizedDescription=data analysis error}
```

**Comment by KuangGang** [comment]
请求广告也是在初始化之后
`void fetchSplashAD() {
    if (Global.isAdInit) {
      loadAd();
    } else {
      AppUtils.initAd().then((value) {
        if (value) {
          loadAd();
        } else {
          finishPage();
        }
      });
    }
  }`

**Comment by KuangGang** [comment]
请求广告也是在初始化之后
<img width="429" alt="image" src="https://github.com/FlutterAds/flutter_gromore_ads/assets/18301340/0bdea165-8723-497f-a7ee-d06283b1cae5">

**Comment by BytesZero** [comment]
是不是新创建的广告位，需要等2小时后再试试

**Comment by KuangGang** [comment]
用的是我线上的广告ID，所以返回这个我也很纳闷，都写的正确

**Comment by BytesZero** [comment]
建议好好看看广告位 id 和对应的广告类型，渲染类型

**Comment by KuangGang** [comment]
> 建议好好看看广告位 id 和对应的广告类型，渲染类型

看了很多遍，就是Gromore的开屏广告位，并且我在线上用的非融合版本sdk用的就是同样的广告位，渲染类型也是自渲染，但是就是会报错，2.1.0版本也升级了，就是报不合法

**Comment by BytesZero** [comment]
@KuangGang 那建议你看看 Pro 版本，然后可以提供专属技术支持，因为这个问题挺个性化的。
https://flutterads.github.io/site/
