### ISSUE TITLE
什么时候出一个支持banner的版本

### ISSUE THREAD

**Issue by bigtotorouk** [FlutterAds/flutter_gromore_ads#5]
什么时候出一个支持banner的版本

**Comment by BytesZero** [comment]
暂时没有计划

**Comment by LuodiJackShen** [comment]
大佬什么时间有空支持下啊

**Comment by BytesZero** [comment]
暂时没有计划，Pro 版本会支持

**Comment by LuodiJackShen** [comment]
pro版本什么时间会出呢？需要收费吗？

**Comment by BytesZero** [comment]
暂时不确定啥时候会出，会收费

**Comment by BytesZero** [comment]
最近灰度测试了 GroMore 的变现能力，提升 3~5 倍

**Comment by BytesZero** [comment]
@LuodiJackShen  穿山甲的 Banner 可以使用我的这个库：https://github.com/FlutterAds/flutter_pangle_ads

**Comment by LuodiJackShen** [comment]
嗯嗯，gromore接入banner是有什么坑或者特别需要时间吗？我们想了解下，如果时间成本还能接受的话，我们准备自己开发下

**Comment by BytesZero** [comment]
这里没有什么建议，可以看看穿山甲 SDK 吧，有参考意义

**Comment by LuodiJackShen** [comment]
好的，谢谢

**Comment by BytesZero** [comment]
已经支持了，但是还没发布版本

**Comment by moujunqiang** [comment]
你好大佬，我引用了您的库自己添加了对draw信息流广告得支持，但是广告显示出来显示在最上层直接遮挡底部操作栏标题栏等，想咨询下您有没有碰到这样的问题，我看其他开源的库信息流广告也有这个问题

**Comment by jimczj** [comment]
> 已经支持了，但是还没发布版本

麻烦发个版本吧，最近刚好有需要 banner
